// PROTOTYPE — wipe me. Stub reference data from docs/provinces.csv and
// docs/disease-groups.md, so the variants render without the API running.
import type { ReferenceData } from '../requester/requester-api';

export const STUB_REFERENCE: ReferenceData = {
  diseaseGroups: [
    { id: 'air-pollution', name: 'โรคจากการสัมผัสมลพิษทางอากาศ' },
    { id: 'silicosis', name: 'โรคซิลิโคสิส' },
    { id: 'asbestos', name: 'โรคจากแร่ใยหิน' },
    { id: 'lead', name: 'โรคจากตะกั่วและสารประกอบของตะกั่ว' },
    { id: 'pesticides', name: 'โรคจากสารกำจัดศัตรูพืช' },
    { id: 'confined-space', name: 'การบาดเจ็บจากภาวะอับอากาศ' },
    { id: 'radiation', name: 'โรคจากรังสี' },
    { id: 'work-related', name: 'โรคจากการทำงาน' },
    {
      id: 'environmental-pollution',
      name: 'โรคที่เกี่ยวข้องกับการสัมผัสมลพิษในสิ่งแวดล้อม',
    },
    { id: 'heat', name: 'โรคจากความร้อน' },
  ],
  provinces: [
    { provinceId: '10', nameTh: 'กรุงเทพมหานคร', healthRegion: 13 },
    { provinceId: '11', nameTh: 'สมุทรปราการ', healthRegion: 6 },
    { provinceId: '12', nameTh: 'นนทบุรี', healthRegion: 4 },
    { provinceId: '13', nameTh: 'ปทุมธานี', healthRegion: 4 },
    { provinceId: '14', nameTh: 'พระนครศรีอยุธยา', healthRegion: 4 },
    { provinceId: '15', nameTh: 'อ่างทอง', healthRegion: 4 },
    { provinceId: '16', nameTh: 'ลพบุรี', healthRegion: 4 },
    { provinceId: '17', nameTh: 'สิงห์บุรี', healthRegion: 4 },
    { provinceId: '18', nameTh: 'ชัยนาท', healthRegion: 3 },
    { provinceId: '19', nameTh: 'สระบุรี', healthRegion: 4 },
    { provinceId: '20', nameTh: 'ชลบุรี', healthRegion: 6 },
    { provinceId: '21', nameTh: 'ระยอง', healthRegion: 6 },
    { provinceId: '22', nameTh: 'จันทบุรี', healthRegion: 6 },
    { provinceId: '23', nameTh: 'ตราด', healthRegion: 6 },
    { provinceId: '24', nameTh: 'ฉะเชิงเทรา', healthRegion: 6 },
    { provinceId: '25', nameTh: 'ปราจีนบุรี', healthRegion: 6 },
    { provinceId: '26', nameTh: 'นครนายก', healthRegion: 4 },
    { provinceId: '27', nameTh: 'สระแก้ว', healthRegion: 6 },
    { provinceId: '30', nameTh: 'นครราชสีมา', healthRegion: 9 },
    { provinceId: '31', nameTh: 'บุรีรัมย์', healthRegion: 9 },
    { provinceId: '32', nameTh: 'สุรินทร์', healthRegion: 9 },
    { provinceId: '33', nameTh: 'ศรีสะเกษ', healthRegion: 10 },
    { provinceId: '34', nameTh: 'อุบลราชธานี', healthRegion: 10 },
    { provinceId: '35', nameTh: 'ยโสธร', healthRegion: 10 },
    { provinceId: '36', nameTh: 'ชัยภูมิ', healthRegion: 9 },
    { provinceId: '37', nameTh: 'อำนาจเจริญ', healthRegion: 10 },
    { provinceId: '39', nameTh: 'หนองบัวลำภู', healthRegion: 8 },
    { provinceId: '40', nameTh: 'ขอนแก่น', healthRegion: 7 },
    { provinceId: '41', nameTh: 'อุดรธานี', healthRegion: 8 },
    { provinceId: '42', nameTh: 'เลย', healthRegion: 8 },
    { provinceId: '43', nameTh: 'หนองคาย', healthRegion: 8 },
    { provinceId: '44', nameTh: 'มหาสารคาม', healthRegion: 7 },
    { provinceId: '45', nameTh: 'ร้อยเอ็ด', healthRegion: 7 },
    { provinceId: '46', nameTh: 'กาฬสินธุ์', healthRegion: 7 },
    { provinceId: '47', nameTh: 'สกลนคร', healthRegion: 8 },
    { provinceId: '48', nameTh: 'นครพนม', healthRegion: 8 },
    { provinceId: '49', nameTh: 'มุกดาหาร', healthRegion: 10 },
    { provinceId: '50', nameTh: 'เชียงใหม่', healthRegion: 1 },
    { provinceId: '51', nameTh: 'ลำพูน', healthRegion: 1 },
    { provinceId: '52', nameTh: 'ลำปาง', healthRegion: 1 },
    { provinceId: '53', nameTh: 'อุตรดิตถ์', healthRegion: 2 },
    { provinceId: '54', nameTh: 'แพร่', healthRegion: 1 },
    { provinceId: '55', nameTh: 'น่าน', healthRegion: 1 },
    { provinceId: '56', nameTh: 'พะเยา', healthRegion: 1 },
    { provinceId: '57', nameTh: 'เชียงราย', healthRegion: 1 },
    { provinceId: '58', nameTh: 'แม่ฮ่องสอน', healthRegion: 1 },
    { provinceId: '60', nameTh: 'นครสวรรค์', healthRegion: 3 },
    { provinceId: '61', nameTh: 'อุทัยธานี', healthRegion: 3 },
    { provinceId: '62', nameTh: 'กำแพงเพชร', healthRegion: 3 },
    { provinceId: '63', nameTh: 'ตาก', healthRegion: 2 },
    { provinceId: '64', nameTh: 'สุโขทัย', healthRegion: 2 },
    { provinceId: '65', nameTh: 'พิษณุโลก', healthRegion: 2 },
    { provinceId: '66', nameTh: 'พิจิตร', healthRegion: 3 },
    { provinceId: '67', nameTh: 'เพชรบูรณ์', healthRegion: 2 },
    { provinceId: '70', nameTh: 'ราชบุรี', healthRegion: 5 },
    { provinceId: '71', nameTh: 'กาญจนบุรี', healthRegion: 5 },
    { provinceId: '72', nameTh: 'สุพรรณบุรี', healthRegion: 5 },
    { provinceId: '73', nameTh: 'นครปฐม', healthRegion: 5 },
    { provinceId: '74', nameTh: 'สมุทรสาคร', healthRegion: 5 },
    { provinceId: '75', nameTh: 'สมุทรสงคราม', healthRegion: 5 },
    { provinceId: '76', nameTh: 'เพชรบุรี', healthRegion: 5 },
    { provinceId: '77', nameTh: 'ประจวบคีรีขันธ์', healthRegion: 5 },
    { provinceId: '80', nameTh: 'นครศรีธรรมราช', healthRegion: 11 },
    { provinceId: '81', nameTh: 'กระบี่', healthRegion: 11 },
    { provinceId: '82', nameTh: 'พังงา', healthRegion: 11 },
    { provinceId: '83', nameTh: 'ภูเก็ต', healthRegion: 11 },
    { provinceId: '84', nameTh: 'สุราษฎร์ธานี', healthRegion: 11 },
    { provinceId: '85', nameTh: 'ระนอง', healthRegion: 11 },
    { provinceId: '86', nameTh: 'ชุมพร', healthRegion: 11 },
    { provinceId: '90', nameTh: 'สงขลา', healthRegion: 12 },
    { provinceId: '91', nameTh: 'สตูล', healthRegion: 12 },
    { provinceId: '92', nameTh: 'ตรัง', healthRegion: 12 },
    { provinceId: '93', nameTh: 'พัทลุง', healthRegion: 12 },
    { provinceId: '94', nameTh: 'ปัตตานี', healthRegion: 12 },
    { provinceId: '95', nameTh: 'ยะลา', healthRegion: 12 },
    { provinceId: '96', nameTh: 'นราธิวาส', healthRegion: 12 },
    { provinceId: '38', nameTh: 'บึงกาฬ', healthRegion: 8 },
  ],
};
