// GENERATED by scripts/generate-province-seed.ts from docs/provinces.csv.
// Do not hand-edit — re-run `pnpm --filter api run db:seed:generate` instead.
import type { ProvinceSeedMeta } from "./province-integrity.js";

export const PROVINCE_SEED_META: ProvinceSeedMeta = {
  rowCount: 77,
  checksum: "a2d0a710b594b931ece4efb508c8e66bc08bc0a816531b287ec283f57926b5ba",
};
