// Regenerates the embedded Data dictionary from `docs/data-dictionary.csv` —
// the canonical source (spec §8.2 rule 8). Run with
// `pnpm --filter api run data-dictionary:generate` whenever
// docs/data-dictionary.csv, docs/disease-groups.md or allowlist.ts's
// EXTRACT_COLUMNS changes. Never hand-edit
// src/reference-data/data-dictionary.generated.ts — it is fully regenerated
// by this script.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { EXTRACT_COLUMNS } from "../src/extraction/allowlist.js";
import { DISEASE_GROUPS } from "../src/reference-data/disease-groups.js";

const CSV_PATH = fileURLToPath(
  new URL("../../../docs/data-dictionary.csv", import.meta.url),
);
const OUTPUT_PATH = fileURLToPath(
  new URL("../src/reference-data/data-dictionary.generated.ts", import.meta.url),
);

/**
 * Cheap drift guard, not a re-parse: every column this build actually
 * writes, and every Disease group id it actually classifies, must appear
 * literally in the checked-in file — otherwise the artifact is stale
 * relative to the code it is meant to document.
 */
function assertCoversCurrentSchema(content: string): void {
  const missingColumns = EXTRACT_COLUMNS.filter((column) => !content.includes(`\n${column},`));
  if (missingColumns.length > 0) {
    throw new Error(
      `docs/data-dictionary.csv is missing column row(s): ${missingColumns.join(", ")}. ` +
        `Update it before regenerating.`,
    );
  }

  const missingGroups = DISEASE_GROUPS.filter((group) => !content.includes(`\n${group.id},`));
  if (missingGroups.length > 0) {
    throw new Error(
      `docs/data-dictionary.csv is missing Disease group row(s): ${missingGroups.map((g) => g.id).join(", ")}. ` +
        `Update it before regenerating.`,
    );
  }
}

function generateOutputFile(content: string): string {
  return (
    `// GENERATED by scripts/generate-data-dictionary.ts from docs/data-dictionary.csv.\n` +
    `// Do not hand-edit — re-run \`pnpm --filter api run data-dictionary:generate\` instead.\n` +
    `export const DATA_DICTIONARY_CSV = ${JSON.stringify(content)};\n`
  );
}

function main(): void {
  const content = readFileSync(CSV_PATH, "utf8");
  assertCoversCurrentSchema(content);
  writeFileSync(OUTPUT_PATH, generateOutputFile(content));
  console.log(`Generated Data dictionary embed (${content.length} bytes of source text).`);
}

main();
