// Regenerates the province seed migration and its checksum metadata from
// `docs/provinces.csv` — the canonical source (spec §6.4, ADR 0002). Run
// with `pnpm --filter api run db:seed:generate` whenever provinces.csv
// changes. Never hand-edit drizzle/migrations/0002_seed_province.sql or
// src/reference-data/province-seed.generated.ts — both are fully
// regenerated by this script.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  computeProvinceChecksum,
  type ProvinceRow,
} from "../src/reference-data/province-integrity.js";

const CSV_PATH = fileURLToPath(
  new URL("../../../docs/provinces.csv", import.meta.url),
);
const MIGRATION_PATH = fileURLToPath(
  new URL("../drizzle/migrations/0002_seed_province.sql", import.meta.url),
);
const META_PATH = fileURLToPath(
  new URL("../src/reference-data/province-seed.generated.ts", import.meta.url),
);
const EXPECTED_ROW_COUNT = 77;

function parseCsv(content: string): ProvinceRow[] {
  const [header, ...lines] = content.trim().split(/\r?\n/);
  const columns = header.split(",");
  if (columns.join(",") !== "province_id,name_th,health_region") {
    throw new Error(`Unexpected provinces.csv header: ${header}`);
  }

  return lines
    .filter((line) => line.length > 0)
    .map((line) => {
      const [provinceId, nameTh, healthRegion] = line.split(",");
      return { provinceId, nameTh, healthRegion: Number(healthRegion) };
    });
}

function sqlStringLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function generateInsertStatements(rows: ProvinceRow[]): string {
  const values = rows
    .map(
      (row) =>
        `(${sqlStringLiteral(row.provinceId)}, ${sqlStringLiteral(row.nameTh)}, ${row.healthRegion})`,
    )
    .join(",\n  ");

  return (
    `-- GENERATED by scripts/generate-province-seed.ts from docs/provinces.csv.\n` +
    `-- Do not hand-edit — re-run \`pnpm --filter api run db:seed:generate\` instead.\n` +
    `INSERT INTO "province" ("province_id", "name_th", "health_region")\nVALUES\n  ${values};\n`
  );
}

function generateMetaFile(rowCount: number, checksum: string): string {
  return (
    `// GENERATED by scripts/generate-province-seed.ts from docs/provinces.csv.\n` +
    `// Do not hand-edit — re-run \`pnpm --filter api run db:seed:generate\` instead.\n` +
    `import type { ProvinceSeedMeta } from "./province-integrity.js";\n\n` +
    `export const PROVINCE_SEED_META: ProvinceSeedMeta = {\n` +
    `  rowCount: ${rowCount},\n` +
    `  checksum: ${JSON.stringify(checksum)},\n` +
    `};\n`
  );
}

function main() {
  const rows = parseCsv(readFileSync(CSV_PATH, "utf8"));

  if (rows.length !== EXPECTED_ROW_COUNT) {
    throw new Error(
      `docs/provinces.csv has ${rows.length} rows, expected ${EXPECTED_ROW_COUNT}. ` +
        `Refusing to generate a seed from an unexpected row count.`,
    );
  }

  const checksum = computeProvinceChecksum(rows);

  writeFileSync(MIGRATION_PATH, generateInsertStatements(rows));
  writeFileSync(META_PATH, generateMetaFile(rows.length, checksum));

  console.log(
    `Generated seed migration and checksum metadata for ${rows.length} provinces.`,
  );
  console.log(`checksum: ${checksum}`);
}

main();
